// <auto-generated />
using BuilderAPIs.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BuilderAPIs.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241012025754_UpdateComponents")]
    partial class UpdateComponents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BuilderAPIs.Domain.Entities.Categories", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryNameEn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CategoryNameEsp")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("BuilderAPIs.Domain.Entities.Components", b =>
                {
                    b.Property<int>("ComponentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ComponentID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("ComponentImage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ComponentNameEn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ComponentNameEsp")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("FrameworkID")
                        .HasColumnType("int");

                    b.HasKey("ComponentID");

                    b.ToTable("Components");
                });

            modelBuilder.Entity("BuilderAPIs.Domain.Entities.FrameworkCategories", b =>
                {
                    b.Property<int>("FrameworkCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FrameworkCategoryId"));

                    b.Property<string>("FrameworkCategoryName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("FrameworkCategoryId");

                    b.ToTable("FrameworkCategories");
                });

            modelBuilder.Entity("BuilderAPIs.Domain.Entities.Frameworks", b =>
                {
                    b.Property<int>("FrameworkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FrameworkId"));

                    b.Property<int>("FrameworkCategoryID")
                        .HasColumnType("int");

                    b.Property<string>("FrameworkName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("FrameworkId");

                    b.ToTable("Frameworks");
                });

            modelBuilder.Entity("BuilderAPIs.Domain.Entities.Items", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<int>("ComponentId")
                        .HasColumnType("int");

                    b.Property<string>("ComponentOrder")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ItemContent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ItemId");

                    b.ToTable("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
